services:
  jeopardy:
    container_name: jeopardy
    image: ghcr.io/oneautumnmango/jeopardy:1.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env.example
    restart: unless-stopped
