services:
  jeopardy:
    container_name: jeopardy
    image: ghcr.io/oneautumnmango/jeopardy:latest
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    env_file:
      - .env.example
    restart: unless-stopped
